### ISSUE TITLE
Cannot login system accounts after installing phplist-plugin-ldap

### ISSUE THREAD

**Issue by ashishvarma04** [digital-me/phplist-plugin-ldap#3]
Only ldap account can login into phplist , but I cannot login phplist accounts .. please help ..!

**Comment by btlogy** [comment]
That's where ldap_except_users is supposed to help (see the README page).
Have you tried to define it with the relevant array for your environment?

**Comment by tfnab** [comment]
The method localValidateLogin is using the wrong constant ENCRYPTION_ALGO. This needs to be changed to HASH_ALGO on lines 38 and 43 of the plugin. I am going to fork and send a pull request later...

**Comment by tfnab** [comment]
It's this change https://github.com/phpList/phplist3/commit/a3a442ba9ed187fe46eeb070239b8ec200d033da of phpList that "broke" the plugin
