### ISSUE TITLE
Plugin Connection

### ISSUE THREAD

**Issue by pmelse** [digital-me/phplist-plugin-ldap#4]
looking at an active directory integration, am I doing this right?
every time I attempt to login, I get an invalid password (even for $ldap_except_users)

contents of config.php 

***
```
// not sure if this line is actually needed:
$admin_auth_mode = '/srv/www/phplist/public_html/lists/config/ldapAuth.php';
//php mailing list
$ldap_enabled = 1;
$ldap_url = "ldap://ad-2012.example.com:389";
$ldap_auth_bind_dn = "cn=ldapphplist,ou=Service Accounts,ou=Some Users,dc=ad,dc=example,dc=com";
$ldap_auth_bind_pw = "supersecurestubhere";
$ldap_all_user_base_dn = "ou=Mailing List Admins,ou=Some Users,dc=ad,dc=example,dc=com";
$ldap_all_user_pattern = "(sAMAccountName=__LOGIN__)";
$ldap_all_user_uid_attribute = "sAMAccountName";
$ldap_all_user_is_super = 1;
$ldap_default_privs = array(
      'subscribers' => true,
      'campaigns' => true,
      'statistics' => true,
      'settings' => true
);
$ldap_matching_user_base_dn = "ou=Mailing List Admins,ou=Some Users,dc=ad,dc=example,dc=com";
$ldap_matching_user_pattern = "(sAMAccountName=__LOGIN__)";
$ldap_matching_user_uid_attribute = "sAMAccountName";
$ldap_except_users = array('admin','admin4');
```

also, what's the best way to debug this on the phplist side?

**Comment by tfnab** [comment]
Your issue with logging in accounts from $ldap_except_users is likely to be the same as issue #3

**Comment by btlogy** [comment]
I bet @tfnab is correct: @pmelse, can you confirm the new master works better now?

**Comment by tfnab** [comment]
@pmelse 
I finally got around to some additional troubleshooting. I found that for the plugin to work with my Active Directory these values in the config file need to be all lowercase:

$ldap_all_user_uid_attribute = "samaccountname";
$ldap_matching_user_uid_attribute = "samaccountname";

**Comment by pmelse** [comment]
@tfnab I have ldap connectivity using the lastest release of phplist with the additions in abc7901284b20ffa471b65e1cb82a07e33ae6241
